# Generated by Django 2.0.3 on 2019-01-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_uum',
            new_name='fav_num',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='click_uum',
            new_name='click_num',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='fav_uum',
            new_name='fav_num',
        ),
    ]
