# Generated by Django 2.1.5 on 2019-02-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190221_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='category',
            new_name='categroy',
        ),
    ]
