# Generated by Django 2.1.5 on 2019-02-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190222_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='click_uum',
            new_name='click_nums',
        ),
    ]
