# Generated by Django 2.1.5 on 2019-02-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190222_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='course_nums',
            new_name='courses',
        ),
    ]
