# Generated by Django 2.0.3 on 2019-02-26 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
