# Generated by Django 2.0.3 on 2019-02-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_teacher_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='add_time',
        ),
    ]
