# Generated by Django 2.0.3 on 2019-02-27 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_remove_courseorg_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='id',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='add_time',
            field=models.AutoField(default=datetime.datetime.now, primary_key=True, serialize=False, verbose_name='添加时间'),
        ),
    ]
