# Generated by Django 2.0.3 on 2019-02-27 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20190227_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
