# Generated by Django 2.0.3 on 2019-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20190227_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
