# Generated by Django 2.0.3 on 2019-02-27 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20190227_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='course_nums',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_nums',
            new_name='fav_num',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='category',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='tag',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='categroy',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='pxjg', max_length=20, verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
