# Generated by Django 2.0.3 on 2019-03-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_courseorg_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='fav_num',
            new_name='fav_nums',
        ),
    ]
