# Generated by Django 2.0.3 on 2019-03-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20190303_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_num',
            new_name='fav_nums',
        ),
    ]
