# Generated by Django 2.0 on 2019-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20, verbose_name='用户名')),
                ('phone_num', models.CharField(max_length=20, verbose_name='手机号')),
                ('passwd', models.CharField(max_length=20, verbose_name='登录密码')),
                ('confirm_passwd', models.CharField(max_length=20, verbose_name='确认密码')),
                ('verfication_code', models.CharField(max_length=6, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '注册新用户',
                'verbose_name_plural': '注册新用户',
            },
        ),
    ]
