# Generated by Django 2.0.3 on 2019-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190224_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_notice',
            field=models.CharField(default='', max_length=500, verbose_name='课程公告'),
        ),
    ]
